version: '3'
services:
  robin:
    image: robin:latest
    ports:
      - "4567:4567"
    container_name: robin

  mongo-db:
    image: mongo
    container_name: 'mongo-db'
    volumes:
        - 'mongodb:/data/db'
        - 'mongodb_config:/data/configdb'
    ports:
        - '27017:27017'
    command: 'mongod'

  service-1:
    image: service:latest
    ports:
      - "4568:4568"
    container_name: service-1

  service-2:
    image: service:latest # Ruta al directorio de Clase2
    ports:
      - "4569:4568"
    container_name: service-2

  service-3:
    image: service:latest # Ruta al directorio de Clase2
    ports:
      - "4570:4568"
    container_name: service-3

volumes:
    mongodb:
    mongodb_config: